<footer class="row">
    <div class="twelve columns"><hr />
        <div class="row">

            <div class="six columns">
                <p>&copy; Copyright no one at all. Go to town.</p>
            </div>

            <div class="six columns">
                <ul class="breadcrumbs">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Features</a></li>
                    <li class="unavailable"><a href="#">Gene Splicing</a></li>
                    <li class="current"><a href="#">Home</a></li>
                </ul>
            </div>

        </div>
    </div>
</footer>
