<footer class="row">
    <div class="twelve columns"><hr />
        <div class="row">

            <div class="six columns">
                <p>&copy; Copyright no one at all. Go to town. Made by <span class="success radius label tiny">cawa</span>, powered by <span class="success radius label tiny">ZF2 Ver. <?php echo \Zend\Version\Version::VERSION ?></span></p>
            </div>

            <div class="six columns">
                <?php
                $this->navigation('Navigation')->menu()->setPartial('partials/breadcrumbs.phtml');
                echo $this->navigation('Navigation')->menu()->render();?>
            </div>
        </div>
    </div>
</footer>
