<nav class="top-bar fixed home-border">
    <ul>
        <li class="name"><h1><a href="<?php echo $this->url('application', []) ?>">Paradebrides</a></h1></li>
        <li class="toggle-topbar"><a href="#"></a></li>
    </ul>
    <section>
        <ul class="left">
            <li><a href="<?php echo $this->url('application/default', ['controller' => 'user']) ?>">Profiles</a></li>
            <li><a class="reveal" href="<?php echo $this->url('application/default', ['controller' => 'user', 'action' => 'new']) ?>" data-reveal-id="registerModal" >Register</a></li>
            <li><a href="<?php echo $this->url('application/default', ['controller' => 'news']) ?>">News</a></li>
        </ul>
        <ul class="right">
            <li><a href="#" data-reveal-id="loginModal">Login</a></li>
            <li>
                <a href="#" data-reveal-id="searchModal">Search</a>
            </li>
            <li class="has-dropdown">
                <a href="#">Link</a>
                <ul class="dropdown">
                    <li><a href="#">Dropdown Link</a></li>
                    <li><a href="#">Dropdown Link</a></li>
                    <li><a href="#">Dropdown Link</a></li>
                </ul>
            </li>
        </ul>
    </section>
</nav><br><br>

<div id="loginModal" class="reveal-modal" style="border: 1px solid black">
    <!-- Test if the User is connected -->
    <?php if (!$this->zfcUserIdentity()): ?>
        <?php echo $this->zfcUserLoginWidget(); ?>
    <?php else: ?>
        <div style="float:left; padding-right:16px;"><?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?></div>
        <h3>Hello, <?php echo $this->zfcUserDisplayName() ?>!</h3>
        <a href="<?php echo $this->url('zfcuser/logout') ?>">[Sign Out]</a>
        <div style="clear:both;"></div>

    <?php endif; ?>
    <a class="close-reveal-modal">&#215;</a>
</div>

<div id="searchModal" class="reveal-modal" style="border: 1px solid black">
    <a class="close-reveal-modal">&#215;</a>
    <form method="POST" action="#">
        <label>Search</label>
        <input type="text"/>
        <input type="submit" value="Search" class="small radius button"/>
    </form>
</div>

<div id="registerModal" style="border: 1px solid black;display: none;" class="row">
</div>

<?php
echo $this->navigation('navigation')->menu()->setUlClass('top-bar fixed home-border');
?>