  <!-- Navigation -->

                <nav class="top-bar contain-to-grid">
                    <ul>
                        <li class="name"><h1><a href="#">Title</a></h1></li>
                        <li class="toggle-topbar"><a href="#"></a></li>
                    </ul>

                    <section>
                        <ul class="left">
                            <li><a href="#">Link 1</a></li>
                            <li><a href="#">Link 2</a></li>
                        </ul>

                        <ul class="right">
                            <li class="search">
                                <form>
                                    <input type="search">
                                </form>
                            </li>

                            <li class="has-button">
                                <a class="small button" href="#">Search</a>
                            </li>
                        </ul>
                    </section>
                </nav>

                <!-- End Navigation -->
