<div id="featuredContent">

    <div>

     <img  src="http://placehold.it/1600x500&text=Slide Image" style="position:absolute; z-index:-1;" alt="slide image">
    <!-- Added jscript run string -->
     <div id="text_anim">This is a Tutorialzine Demo! </div>
     </div>

    <div>
        <img src="http://placehold.it/1600x500&text=Slide Image" alt="slide image">
    </div>
    <div>
        <img src="http://placehold.it/1600x500&text=Slide Image" alt="slide image">
    </div>

</div>
