<div id="featuredContent" >

    <div>

     <img  src="/images/carousel/<?php echo rand(1, 25) ?>.jpg" style="position:absolute; z-index:-1;" alt="slide image">
    <!-- Added jscript run string -->
     <div id="text_anim">This is a Tutorialzine Demo! </div>
     </div>

    <div>
        <img src="/images/carousel/<?php echo rand(1, 25) ?>.jpg" style="position:absolute; z-index:-1;" alt="slide image">
        <div id="text_anim">This is a Tutorialzine Demo! </div>
    </div>
    <div>
        <img src="/images/carousel/<?php echo rand(1, 25) ?>.jpg" style="position:absolute; z-index:-1;" alt="slide image">
        <div id="text_anim">This is a Tutorialzine Demo! </div>
    </div>

</div>
