<style>
    .panel:hover{
        border: solid 1px #CCC;
	-moz-box-shadow: 1px 1px 5px #999;
	-webkit-box-shadow: 1px 1px 5px #999;
        box-shadow: 1px 1px 5px #999;
    }
</style>
<div class="row">
<?php foreach ($this->users as $user): ?>
    
    <div class="three">
        <span class="has-tip tip-bottom" style="border-bottom: none;" title="<?php echo 'Click on avatar to view '.$user->getrealname() ?>">
        <div  class="panel">
            <a href="<?php echo $this->url('application/default',
                                            ['controller' => 'user',
                                                'action' => 'info'])
                    . '?email=' . $user->getemail() ?>">
                <img src="http://placehold.it/100x100&text=User photo"></a>
            <h6 class="right">Name: <?php echo $user->getrealname() ?> <br> Country:<?php echo $user->getCountry() ?></h6>
            <p style="color: black">Birth:  <?php echo ($user->getBirth()->format('d/M/Y')) ?><br>
            User email:<?php echo $user->getemail() ?></p>
        </div>
         </span>
    </div>
    
<?php endforeach; ?>
</div>