  <!-- Side Bar -->

        <div class="four mobile-four columns">

          <img src="http://placehold.it/300x300&text=AVATAR">

          <div class="hide-for-small panel">
              <h3><?php echo $this->user->getemail() ?></h3>
            </h5>
          </div>

         

        </div>

    <!-- End Side Bar -->


    <!-- Thumbnails -->
    
        <div class="eight columns">
            <div class="row">
                <ul data-clearing> 
      <?php //if(is_array($this->images)) ?>          
       <?php foreach ($this->images as $img): ?>
         <li>
            <div class="four mobile-two columns">
              <img src="<?php echo $img ?>">

              <div class="panel">
                <h5><?php $img ?></h5>
              </div>
            </div>
         </li>    
        <?php endforeach; ?>        
          </ul>          
   <!-- End Thumbnails -->


    <!-- Managed By -->

            <div class="twelve columns">
              <div class="panel">
                <div class="row">

                  <div class="two mobile-two columns">
                    <img src="http://placehold.it/300x300&text=Site Owner">
                  </div>

                  <div class="ten mobile-two columns">
                    <strong>This Site Is Managed By<hr/></strong>

                    Risus ligula, aliquam nec fermentum vitae, sollicitudin eget urna. Donec dignissim nibh fermentum odio ornare sagittis
                  </div>

                </div>
              </div>
            </div>

    <!-- End Managed By -->

          </div>
        </div>
      </div>


