<div class="modal hide fade" id="<?php echo $this->id ?>">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3><?php echo isset($this->caption) ? $this->caption : NULL ?></h3>
    </div>
    <div class="modal-body">
        <?php echo isset($this->body) ? $this->body : '' ?>
    </div>
    <?php if($this->buttons): ?>
         <div class="modal-footer">
          <?php foreach($this->buttons as $button): ?>
        <a class="btn" <?php
                        if(isset($button['href'])){
                            echo 'href='.'"'.$button['href'].'"';
                        }else{
                           echo 'data-dismiss="modal"';}
                echo '>'.$this->_($button['text']); ?></a>
       <?php endforeach; endif;?>
    </div>
</div>
