<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Главная')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico')) ?>
        <?php echo $this->headScript() . PHP_EOL ?>
    </head>
    <body>
        <div class="row">
            <div class="twelve columns">
                <?php echo $this->partial('partials/navigation'); ?>
            </div>
        </div>
        <div class="row">
            <div class="twelve columns">
                <?php echo $this->partial('partials/slider') ?>
            </div>
        </div><br>
        <?php echo $this->layout()->content ?>
    </div>
</div>
</div>
<?php echo $this->partial('partials/footer') ?>
<!-- Included JS Files -->
<script type="text/javascript">
    $(window).load(function() {
        $('#featured').orbit({ fluid: '2x1' });
    });
</script>
</body>
</html>
