<div class="eleven columns centered"><?php echo $this->partial('/partials/slider') ?></div>

<div class="row">

    <div class="three panel columns">
        <img src="http://placehold.it/500x500&text=Best girl">

        <h4>Header</h4>

        <p>Fusce ullamcorper mauris in eros dignissim molestie posuere felis blandit. Aliquam erat volutpat. Mauris ultricies posuere vehicula. Sed sit amet posuere erat. Quisque in ipsum non augue euismod dapibus non et eros.</p><hr>

        <div class="row">
            <div class="four columns">
                <a href="#" class="small button">Link</a>
            </div>

            <div class="four columns">
                <a href="#" class="small button">Link</a>
            </div>

            <div class="four columns">
                <a href="#" class="small button">Link</a>
            </div>
        </div>
    </div>

    <div class="nine columns">
        <div class="panel">
            <div class="row">
                <dl class="tabs">
                    <dd ><a href="#simple1">Simple Tab 1</a></dd>
                    <dd><a href="#simple2">Simple Tab 2</a></dd>
                    <dd class="hide-for-small"><a href="#simple3">Simple Tab 3</a></dd>
                </dl>
                <ul class="tabs-content">
                    <li id="simple1Tab">This is simple tab 1s content. Pretty neat, huh?</li>
                    <li id="simple2Tab">This is simple tab 2s content. Now you see it!</li>
                    <li id="simple3Tab">This is simple tab 3s content.</li>
                </ul>
                <div class="three columns">
                    <img src="http://placehold.it/600x500&text=Thumbnail">
                </div>

                <div class="three columns">
                    <img src="http://placehold.it/600x500&text=Thumbnail">
                </div>

                <div class="three columns">
                    <img src="http://placehold.it/600x500&text=Thumbnail">
                </div>

                <div class="three columns">
                    <img src="http://placehold.it/600x500&text=Thumbnail">
                </div>

                <div class="three columns">
                    <img src="http://placehold.it/600x500&text=Thumbnail">
                </div>

                <div class="three columns">
                    <img src="http://placehold.it/600x500&text=Thumbnail">
                </div>

                <div class="three columns">
                    <img src="http://placehold.it/600x500&text=Thumbnail">
                </div>

                <div class="three columns">
                    <img src="http://placehold.it/600x500&text=Thumbnail">
                </div>

                <div class="three columns">
                    <img src="http://placehold.it/600x500&text=Thumbnail">
                </div>

                <div class="three columns">
                    <img src="http://placehold.it/600x500&text=Thumbnail">
                </div>

                <div class="three columns">
                    <img src="http://placehold.it/600x500&text=Thumbnail">
                </div>

                <div class="three columns end">
                    <img src="http://placehold.it/600x500&text=Thumbnail">
                </div>
            </div>
        </div>

        <div class="row">
            <div class="six columns">
                <div class="panel">
                    <h5>Subheader</h5>
                    <p>Sed sit amet posuere erat. Quisque in ipsum non augue euismod dapibus non et eros.</p>
                    <a href="#" class="small button">Link</a>
                </div>
            </div>

            <div class="six columns">
                <div class="panel">
                    <h5>Subheader</h5>
                    <p>Sed sit amet posuere erat. Quisque in ipsum non augue euismod dapibus non et eros.</p>
                    <a href="#" class="small button">Link</a>
                </div>
            </div>
        </div>
    </div>

</div>